services:
  mathflix:
    image: ghcr.io/ferilee/mathflix2:latest
    container_name: mathflix2-prod
    ports:
      - "9111:80"
    env_file:
      - .env
    environment:
      - VITE_API_URL=/api
    networks:
      - ferileenet
    restart: unless-stopped

networks:
  ferileenet:
    external: true
