services:
  frontend:
    build:
      context: .
    container_name: mathflix-frontend
    ports:
      - "9111:80"
    env_file:
      - .env
    networks:
      - ferileenet
    restart: always
    depends_on:
      - api

  api:
    build:
      context: ./api
    container_name: mathflix-api
    ports:
      - "3002:3000"
    env_file:
      - .env
    networks:
      - ferileenet
    volumes:
      - ./api/data:/app/data
    restart: always

networks:
  ferileenet:
    external: true
