services:
  mathflix:
    image: ghcr.io/ferilee/mathflix2-frontend:latest
    container_name: mathflix2-prod
    ports:
      - "9111:80"
    env_file:
      - .env
    environment:
      - VITE_API_URL=/api
    networks:
      - ferileenet
    restart: unless-stopped
    depends_on:
      - api

  api:
    image: ghcr.io/ferilee/mathflix2-api:latest
    container_name: mathflix2-api
    env_file:
      - .env
    volumes:
      - ./api/data:/app/data
    networks:
      - ferileenet
    restart: unless-stopped

networks:
  ferileenet:
    external: true
